### PR TITLE
[EngineSigner]: don't sign message with only zeroes

### LINKED ISSUE #11521: parity build from master branch not work when use POA,No valid password for the consensus signer!
Hey ! I can not use parity build from master to run below POA node, it always show
password not right even the password is OK,and the problem is build from master branch.
When I build from  https://github.com/OpenEthereum/open-ethereum/archive/v2.7.2.tar.gz
it can run and start node normally, so Why master branch not work, or may be a latent bug?
The POA node script is from https://wiki.parity.io/Validator-Set-Tutorial-Overview
- **Parity Ethereum version**: v2.8.0
   build from master  branch source

- **reproduce step**
```
$ git clone https://github.com/OpenEthereum/open-ethereum.git
$ cd OpenEthereum
$ cargo build --release --features final

# the parity created ok
$ ls -ltr target/release/
合計 136388
drwxrwxr-x.   2        6  2月 26 12:32 incremental
drwxrwxr-x.   2        6  2月 26 12:32 examples
drwxrwxr-x. 104     8192  2月 26 12:32 build
-rw-rw-r--.   2 94330720  2月 26 14:06 libparity_ethereum.rlib
-rwxrwxr-x.   2 45135480  2月 26 14:15 parity
drwxrwxr-x.   2    73728  2月 26 14:15 deps
-rw-rw-r--.   1    36792  2月 26 14:15 libparity_ethereum.d
-rw-rw-r--.   1    36819  2月 26 14:15 parity.d

$ git branch
* master

#OS
$ uname -a
Linux pb-app-01 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ ./parity  --version
Parity Ethereum Client.
  version Parity-Ethereum/v2.8.0-nightly-cd70180-20200225/x86_64-unknown-linux-gnu/rustc1.41.0
Copyright 2015-2020 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwi?ga/Volf/Greeff
   Habermeier/Czaban/Gotchac/Redman/Nikolsky
   Schoedon/Tang/Adolfsson/Silva/Palm/Hirsz et al.

$ git clone https://github.com/Tbaut/Validator-set-tutorial.git
$ cd ~/Validator-set-tutorial/Full-setup
$bash start.sh
Loading config file from ./node0.toml
2020-02-26 18:56:19  Running AuRa with a single validator implies instant finality. Use a database?
2020-02-26 18:56:19  Starting Parity-Ethereum/v2.8.0-nightly-cd70180-20200225/x86_64-unknown-linux-gnu/rustc1.41.0
2020-02-26 18:56:19  Keys path node0/keys/Validator-set-tutorial
2020-02-26 18:56:19  DB path node0/chains/Validator-set-tutorial/db/fef38a67cfcd0963
2020-02-26 18:56:19  State DB configuration: fast
2020-02-26 18:56:19  Operating mode: active
No valid password for the consensus signer 0xa292…d64a. Make sure valid password is present in files passed using `--password` or in the configuration file.
```

### PR DESCRIPTION
**Pull request by niklasad1**
Fixes #11521

At startup the `engine_signer(s)` are tested that they can sign `dummy data`, previously only zeroes were signed to check this. After switching to `upstream rust-secp256k1` signing only zeroes doesn't work which this PR fixes.

### CODE REVIEW

File: parity/account_utils.rs [hunk 1]
```diff
@@ -152,8 +152,9 @@ mod accounts {
 				engine_signer,
 				password.clone(),
 			);
-			if signer.sign(Default::default()).is_ok() {
-				author = Some(::ethcore::miner::Author::Sealer(Box::new(signer)));
+			// NOTE: rust-secp256k1, a Message cannot be all zeroes anymore
+			if signer.sign([1_u8; 32].into()).is_ok() {
```
Comment (dvdplm) [inline parity/account_utils.rs]: Good catch. `Default::default()` is a rust idiom I really don't like, it's too clever for its own good. Can we also do something better than just fail silently, i.e. `warn!` if the dummy signing fails?

Comment (niklasad1) [reply parity/account_utils.rs]: > Default::default() is a rust idiom I really don't like, it's too clever for its own good

Agree, it is quite elegant not to have to import specific type and so on ..., but bad for readability.

We are actually printing, `No valid password for the consensus signer {}. {}", engine_signer, VERIFY_PASSWORD_HINT` when this fails in `parity::execute_impl`. Is that not sufficient or do you want to log each failed `dummy sign` attempt? It may be noisy if several passwords are used

The reported error is bad, https://github.com/OpenEthereum/open-ethereum/blob/master/rpc/src/v1/helpers/engine_signer.rs#L41.

Comment (dvdplm) [reply parity/account_utils.rs]: > We are actually printing, No valid password for the consensus signer

Yeah, it's just that it's not their password that is the problem, but the payload.

I guess it's kind of moot now that you've fixed it so let's just leave it.

I'd remove the comment though, or do you think it's useful?

Comment (dvdplm) [reply parity/account_utils.rs]: …or maybe add a `const DUMMY_SECP_MESSAGE` and slap a big comment there?

Comment (niklasad1) [reply parity/account_utils.rs]: I don't think the comment is necessary, it was more for  you reviewers.

A constant is better and self-explained, self-documenting code for the win :muscle:

File: parity/account_utils.rs [hunk 2]
```diff
@@ -145,22 +147,25 @@ mod accounts {
...
 				engine_signer,
 				password.clone(),
 			);
-			if signer.sign(Default::default()).is_ok() {
-				author = Some(::ethcore::miner::Author::Sealer(Box::new(signer)));
+			if let Err(e) = signer.sign(SECP_TEST_MESSAGE) {
+				debug!(target: "account", "Signing test of `EngineSigner ({})` with password index: {} failed because of: {:?}", engine_signer, idx, e);
+				invalid_reasons.insert(e.to_string());
+			} else {
+				return Ok(Some(ethcore::miner::Author::Sealer(Box::new(signer))));
```
Comment (niklasad1) [inline parity/account_utils.rs]: once we have found a valid password then return it directly, no need to iterate over the rest.

File: parity/account_utils.rs [hunk 3]
```diff
@@ -145,22 +147,25 @@ mod accounts {
...
 			}
 		}
-		if author.is_none() {
-			return Err(format!("No valid password for the consensus signer {}. {}", engine_signer, VERIFY_PASSWORD_HINT));
-		}
 
-		Ok(author)
+		Err(format!(
```
Comment (niklasad1) [inline parity/account_utils.rs]: This will look like:

```bash
No valid password found for EngineSigner 0x5100…cae4, the following errors were found during testing: {"custom crypto error: invalid AES message", "custom crypto error: Invalid password"}. Make sure valid password is present in files passed using `--password` or in the configuration file.
```

File: rpc/src/v1/helpers/engine_signer.rs [hunk 4]
```diff
@@ -36,16 +36,14 @@ impl EngineSigner {
 
 impl engine::signer::EngineSigner for EngineSigner {
 	fn sign(&self, message: Message) -> Result<Signature, Error> {
-		match self.accounts.sign(self.address, Some(self.password.clone()), message) {
-			Ok(ok) => Ok(ok),
-			Err(_) => Err(Error::InvalidSecretKey),
-		}
+		self.accounts.sign(self.address, Some(self.password.clone()), message).map_err(|e| {
+			Error::Custom(e.to_string())
```
Comment (niklasad1) [inline rpc/src/v1/helpers/engine_signer.rs]: propagate real error cause instead of making assumptions.

File: rpc/src/v1/helpers/engine_signer.rs [hunk 5]
```diff
@@ -36,16 +36,14 @@ impl EngineSigner {
...
+		})
 	}
 
 	fn decrypt(&self, auth_data: &[u8], cipher: &[u8]) -> Result<Vec<u8>, Error> {
 		self.accounts.decrypt(self.address, None, auth_data, cipher).map_err(|e| {
-			warn!("Unable to decrypt message: {:?}", e);
```
Comment (niklasad1) [inline rpc/src/v1/helpers/engine_signer.rs]: Removed this, because it is better that the caller handles this error accordingly. Thoughts?

File: parity/account_utils.rs [hunk 6]
```diff
@@ -145,22 +147,25 @@ mod accounts {
...
 			let signer = parity_rpc::signer::EngineSigner::new(
 				account_provider.clone(),
 				engine_signer,
 				password.clone(),
 			);
-			if signer.sign(Default::default()).is_ok() {
-				author = Some(::ethcore::miner::Author::Sealer(Box::new(signer)));
+			if let Err(e) = signer.sign(SECP_TEST_MESSAGE) {
+				debug!(target: "account", "Signing test of `EngineSigner ({})` with password index: {} failed because of: {:?}", engine_signer, idx, e);
+				invalid_reasons.insert(e.to_string());
```
Comment (niklasad1) [inline parity/account_utils.rs]: `parity_crypto::public::Error` doesn't impl `Eq`, that's why it is converted to a String

Comment (dvdplm) [reply parity/account_utils.rs]: Maybe it should? :)
